#!/bin/bash

if [[ $1 == "reboot" ]]; then
	apt-get update -y && apt-get upgrade -y && apt-get autoremove -y && apt-get dist-upgrade -y && do-release-upgrade -d;
	reboot;
elif [[ $1 == "shutdown" ]]; then
	apt-get update -y && apt-get upgrade -y && apt-get autoremove -y && apt-get dist-upgrade -y && do-release-upgrade -d;
	shutdown -h now;
else
	apt-get update -y && apt-get upgrade -y && apt-get autoremove -y && apt-get dist-upgrade -y && do-release-upgrade -d
fi


# unless you're a root, it is recommended to execute this command with "sudo -i"